### ISSUE TITLE
Ideas list to discuss

### ISSUE THREAD

**Issue by zrks** [devopslv/home#7]
Please add here ideas to discuss in devopslv meeting

**Comment by AndrisJrs** [comment]
Configuration - What ports are we running for our app? Firewall - is there scaleway solution or we must use iptables to expose ports that are required? How we will deploy containers? What CI solution we will use?

**Comment by neb0t** [comment]
Will we plane ChantOps, Popular online service integrations (Twitter, RSS, email news etc)? Will we create new accounts for those things.

**Comment by neb0t** [comment]
Groovy DSL for Jenkins jobs?
Which pipeline steps we will/should have?

**Comment by neb0t** [comment]
From my point of view, we could have next steps for new document/news release :
- [Create (create new doc).] 
- [Validate (check syntax errors, sources, copy rights end so on).] 
- [Post (post doc on the main page).]

**Comment by ArtursL** [comment]
All of that will take some time to set up...
How about we use some simple static hosting like GitHub Pages or an S3 bucket so that we can start working on content in the meantime?

**Comment by zrks** [comment]
Yes - we surely can do this - idea is to have some sort of playground for devops - but content shouldn't be forgotten too

**Comment by angelcharge** [comment]
TDD for IaC.
But let's have some initial content
